AWSTemplateFormatVersion: '2010-09-09'
Description: 'NebengJek Database Stack - Simplified for Assessment'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: The deployment environment

  VpcId:
    Type: String
    Description: VPC where the resources will be deployed

  PrivateSubnet1:
    Type: String
    Description: First private subnet

  PrivateSubnet2:
    Type: String
    Description: Second private subnet

  DatabaseMasterUsername:
    Type: String
    Default: admin
    Description: Database master username
    NoEcho: true

  DatabaseMasterPassword:
    Type: String
    Description: Database master password
    NoEcho: true
    MinLength: 8

  DatabaseInstanceClass:
    Type: String
    Default: db.t3.micro
    Description: The database instance class
    AllowedValues:
      - db.t3.micro
      - db.t3.small
      - db.t3.medium

Resources:
  # Security Group for RDS - Self-contained
  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for RDS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 10.0.0.0/16 # Allow from entire VPC
          Description: PostgreSQL access from VPC
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-database-sg'

  # Database Subnet Group
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DB subnet group for NebengJek
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-database-subnet-group'

  # PostgreSQL RDS Instance - Single database, multiple schemas
  PostgreSQLInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete # For assessment only
    Properties:
      AllocatedStorage: 20
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      BackupRetentionPeriod: 1 # Minimal for assessment
      DBInstanceClass: !Ref DatabaseInstanceClass
      DBInstanceIdentifier: !Sub '${Environment}-nebengjek-db'
      DBName: nebengjek
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      Engine: postgres
      EngineVersion: '13.13'
      MasterUsername: !Ref DatabaseMasterUsername
      MasterUserPassword: !Ref DatabaseMasterPassword
      MultiAZ: false # Single AZ for assessment
      Port: 5432
      PubliclyAccessible: false
      StorageEncrypted: false # Simplified for assessment
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-nebengjek-db'

Outputs:
  DatabaseEndpoint:
    Description: Endpoint of the RDS instance
    Value: !GetAtt PostgreSQLInstance.Endpoint.Address
    Export:
      Name: !Sub '${Environment}-DatabaseEndpoint'

  DatabasePort:
    Description: Port of the RDS instance
    Value: !GetAtt PostgreSQLInstance.Endpoint.Port
    Export:
      Name: !Sub '${Environment}-DatabasePort'

  DatabaseName:
    Description: Database name
    Value: nebengjek
    Export:
      Name: !Sub '${Environment}-DatabaseName'

  DatabaseUsername:
    Description: Database master username
    Value: !Ref DatabaseMasterUsername
    Export:
      Name: !Sub '${Environment}-DatabaseUsername'

  DatabaseSecurityGroupId:
    Description: Security Group ID for Database
    Value: !Ref DatabaseSecurityGroup
    Export:
      Name: !Sub '${Environment}-DatabaseSecurityGroupId'
