AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal Notification Service - No IAM/ECS Creation'

Parameters:
  Environment:
    Type: String
    Default: dev

  VpcId:
    Type: String
    Description: VPC ID
    Default: vpc-021b849d6600dd8b7

  PrivateSubnet1:
    Type: String
    Description: Private subnet 1
    Default: subnet-xxx # You need to get this from VPC stack

  PrivateSubnet2:
    Type: String
    Description: Private subnet 2
    Default: subnet-yyy # You need to get this from VPC stack

Resources:
  # Only create what we CAN create (EC2 and Logs resources)

  NotificationServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Notification Service
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3004
          ToPort: 3004
          CidrIp: 10.0.0.0/16
          Description: Notification Service HTTP port
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-notification-service-sg'

  NotificationServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${Environment}/notification-service'
      RetentionInDays: 7

  # Target Group for Load Balancer (if ALB exists)
  NotificationServiceTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${Environment}-notification-tg'
      Port: 3004
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckEnabled: true
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-notification-service-tg'

Outputs:
  SecurityGroupId:
    Description: Security Group ID for Notification Service
    Value: !Ref NotificationServiceSecurityGroup
    Export:
      Name: !Sub '${Environment}-NotificationServiceSecurityGroup'

  LogGroupName:
    Description: CloudWatch Log Group for Notification Service
    Value: !Ref NotificationServiceLogGroup
    Export:
      Name: !Sub '${Environment}-NotificationServiceLogGroup'

  TargetGroupArn:
    Description: Target Group ARN for Notification Service
    Value: !Ref NotificationServiceTargetGroup
    Export:
      Name: !Sub '${Environment}-NotificationServiceTargetGroup'
