AWSTemplateFormatVersion: '2010-09-09'
Description: 'NebengJek User Service - Updated for External Database'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

  VpcId:
    Type: String
    Description: VPC ID where services will be deployed

  PrivateSubnet1:
    Type: String
    Description: First private subnet for ECS tasks

  PrivateSubnet2:
    Type: String
    Description: Second private subnet for ECS tasks

  ECSClusterName:
    Type: String
    Description: Name of the ECS cluster

  ECRRepository:
    Type: String
    Default: user-service
    Description: ECR repository name for user service

  # External Database Parameters (from nebengjek-db deployment)
  DatabaseEndpoint:
    Type: String
    Default: nebengjek-prod-postgres.cbw0ge6eg2a8.ap-southeast-1.rds.amazonaws.com
    Description: RDS PostgreSQL endpoint

  DatabasePort:
    Type: String
    Default: '5432'
    Description: Database port

  DatabaseName:
    Type: String
    Default: nebengjek_prod
    Description: Database name

  DatabaseUsername:
    Type: String
    Default: nebengjek
    Description: Database username

  DatabasePassword:
    Type: String
    NoEcho: true
    Description: Database password (store in secrets manager)

  # Optional Redis Parameters
  RedisHost:
    Type: String
    Default: 'redis.nebengjek.local'
    Description: Redis host (external or ElastiCache)

  RedisPort:
    Type: String
    Default: '6379'
    Description: Redis port

Resources:
  # Security Group for User Service
  UserServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for User Service
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3001
          ToPort: 3001
          CidrIp: 10.0.0.0/16
          Description: HTTP access from VPC
        - IpProtocol: tcp
          FromPort: 8008
          ToPort: 8008
          CidrIp: 10.0.0.0/16
          Description: TCP microservice access
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-user-service-sg'

  # IAM Role for ECS Task
  UserServiceTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: UserServicePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              # Add additional permissions as needed

  # ECS Task Definition
  UserServiceTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${Environment}-user-service'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref UserServiceTaskRole
      TaskRoleArn: !Ref UserServiceTaskRole
      ContainerDefinitions:
        - Name: user-service
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:latest'
          PortMappings:
            - ContainerPort: 3001
              Protocol: tcp
            - ContainerPort: 8008
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: USER_PORT
              Value: '3001'
            - Name: USER_TCP_PORT
              Value: '8008'
            - Name: DATABASE_URL
              Value: !Sub 'postgresql://${DatabaseUsername}:${DatabasePassword}@${DatabaseEndpoint}:${DatabasePort}/${DatabaseName}?sslmode=require'
            - Name: REDIS_HOST
              Value: !Ref RedisHost
            - Name: REDIS_PORT
              Value: !Ref RedisPort
            - Name: JWT_ACCESS_SECRET
              Value: 'secure_jwt_access_secret_change_in_production'
            - Name: JWT_REFRESH_SECRET
              Value: 'secure_jwt_refresh_secret_change_in_production'
            - Name: GATEWAY_SECRET_KEY
              Value: 'secure_gateway_secret_change_in_production'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref UserServiceLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: user-service
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3001/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  # CloudWatch Log Group
  UserServiceLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${Environment}/user-service'
      RetentionInDays: 30

  # ECS Service
  UserService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${Environment}-user-service'
      Cluster: !Ref ECSClusterName
      TaskDefinition: !Ref UserServiceTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref UserServiceSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          AssignPublicIp: DISABLED
      HealthCheckGracePeriodSeconds: 60
      EnableExecuteCommand: true
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-user-service'

  # Service Discovery (Optional)
  UserServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: user-service
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 10
        NamespaceId: !Ref ServiceDiscoveryNamespace
      HealthCheckCustomConfig:
        FailureThreshold: 1

  ServiceDiscoveryNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties:
      Name: !Sub '${Environment}.nebengjek.local'
      Vpc: !Ref VpcId

Outputs:
  UserServiceName:
    Description: Name of the User Service
    Value: !Ref UserService
    Export:
      Name: !Sub '${Environment}-UserService'

  UserServiceSecurityGroup:
    Description: Security Group of User Service
    Value: !Ref UserServiceSecurityGroup
    Export:
      Name: !Sub '${Environment}-UserServiceSecurityGroup'

  ServiceDiscoveryNamespace:
    Description: Service Discovery Namespace
    Value: !Ref ServiceDiscoveryNamespace
    Export:
      Name: !Sub '${Environment}-ServiceDiscoveryNamespace'
