export enum ServiceType {
  USER_SERVICE = 'USER_SERVICE',
  BOOKING_SERVICE = 'BOOKING_SERVICE',
  MATCHING_SERVICE = 'MATCHING_SERVICE',
  PAYMENT_SERVICE = 'PAYMENT_SERVICE',
  NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
  TRACKING_SERVICE = 'TRACKING_SERVICE',
}
